### ISSUE TITLE
Not recognizing a .nomnoml document

### ISSUE THREAD

**Issue by cfjedimaster** [doctorrustynelson/vscode-nomnoml#1]
I added a new document called foo.nomnoml. I copied the code from http://www.nomnoml.com/, but the extension doesn't recognize it. Screen shot: (please ignore the rest of the folder, it was just a temp folder of a old project):

![image](https://cloud.githubusercontent.com/assets/393660/15621003/850c1f34-2423-11e6-8adc-c9702a178f75.png)

**Comment by doctorrustynelson** [comment]
It looks to me like vscode has not assigned the nomnoml languageId to your file.  This sometimes happens with a new file and I've been able to fix it by closing the file and extension and re-opening it and rerunning the extension.  You should see on the language id in the footer when you open the file.  I've also pushed out a new version of the extension with better errors to help things like this.
