### ISSUE TITLE
The "implementation" and "generalization" links are rendered in the same manner

### ISSUE THREAD

**Issue by Hunter21007** [doctorrustynelson/vscode-nomnoml#3]
This code should produce a diagram where 
- links for "<:-" are rendered with solid lines
- links for "<:--" are rendered with dashes

```
  [EntityBase]<:-[MetaDataRecordBase]
    [IMetaDataRecord]<:--[MetaDataRecordBase|
        Name:string;
        Title:string;
        Description:string
    ]
```

same applies to association and dependency links

Actually all links a rendered with solid lines. 
Since the plugin uses nomnoml module for rendering diagram, the issue is actually should be addressed to it.

maybe this could be fixed by using newer version (if exist)

**Comment by doctorrustynelson** [comment]
I suspect this has to do with how the nomnoml module is generating the svg getting injected into the view.  Unfortunately there is no newer version of the module at this time to upgrade to.

**Comment by skanaar** [comment]
The SVG implementation in nomnoml is (as you observe) still in its infancy. I would gladly accept help in that area if any of you are interested in sending a pull request.

**Comment by Hunter21007** [comment]
Just for a question, because i have no clue right now:
Vscode is based on WebKit, why not to use canvas?
(I can imagine it is impossible due to restrictions on vscode side, so this is just for clarifications)

This would make the web app and this plugin to use same rendering capabilities. (Probably)

**Comment by Hunter21007** [comment]
@skanaar

I have no clue about svg, but I have read the code and found that the function 

setLineDash: function (){},

Is empty, where it is needed to set 

SVG stroke-dasharray Property 
http://www.w3schools.com/svg/svg_stroking.asp

I think (at time of typing I have only my smartphone on hands and can not test anything, sorry)

Maybe this helps in some way

**Comment by Hunter21007** [comment]
I close the issue because it definitely addressed to nomnoml
